[package]
name = "RenegadesPresale"
version = "1.0.0"
authors = []

[addresses]
rena_multisig = "0x40144de4df2e11328fca954ca18b1294d406f0378c7831ff9c6f6513f262e113"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Rena]
git = "https://github.com/TowneSquare/RENA-smart-contract.git"
rev = "main"
subdir = "core"

[dev-dependencies]

